projects:
  # 'app-core':
  #   schema: ['https://api.boson.health/graphql']
  #   documents: ['apps/app/**/*.{graphql,js,ts,jsx,tsx}']

  # 'app-v2':
  #   schema: ['http://clinical-api.tau.health:8080/graphql']
  #   documents: ['apps/app/**/SettingsV2/**/*.{ts,tsx}']
  #   extensions: { languageService: { cacheSchemaFileForLookup: true } }
  'app-v2':
    schema: ['http://clinical-api.boson.health/graphql']
    documents: ['apps/app/**/Settings/**/*.{ts,tsx}']
    extensions: { languageService: { cacheSchemaFileForLookup: true } }
