/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  fragment NetworkPrescriptionFields on Prescription {\n    id\n    status\n    treatment {\n      id\n      name\n      rxNormId\n      ndc\n    }\n    instructions\n    dispense {\n      quantity\n      unit\n      daysSupply\n      refillsAllowed\n      dispenseAsWritten\n    }\n    clinical {\n      notes\n      diagnoses {\n        icd10Code\n      }\n    }\n    screeningAlerts {\n      severity\n      type\n      description\n    }\n    signing {\n      state\n      contentHash\n    }\n  }\n": typeof types.NetworkPrescriptionFieldsFragmentDoc,
    "\n  fragment NetworkChangeFields on Change {\n    key\n    label\n    status\n    severity\n    reason\n  }\n": typeof types.NetworkChangeFieldsFragmentDoc,
    "\n  fragment DraftOrderQuestionFields on OrderQuestion {\n    id\n    key\n    text\n    reason\n    authorOrganizationId\n    answer {\n      text\n      boolean\n      date\n      choices\n    }\n    answeredAt\n    createdAt\n  }\n": typeof types.DraftOrderQuestionFieldsFragmentDoc,
    "\n  fragment DraftOrderClaimFields on PhotonPpDraftOrder {\n    id\n    createdAt\n    claim {\n      organizationId\n      claimedAt\n      waitingForPatient\n      patientId\n      claimedByUserId\n      claimedByMe\n    }\n    outcome {\n      status\n      closedAt\n      orderId\n      rejectionReason\n    }\n  }\n": typeof types.DraftOrderClaimFieldsFragmentDoc,
    "\n  fragment DraftOrderSummaryFields on PhotonPpDraftOrder {\n    ...DraftOrderClaimFields\n    order {\n      id\n      state\n      patient {\n        __typename\n        ... on Patient {\n          id\n          demographic {\n            name {\n              first\n              last\n            }\n            dateOfBirth\n            address {\n              state\n            }\n          }\n        }\n      }\n      prescriptions {\n        id\n        treatment {\n          id\n          name\n        }\n      }\n      questions {\n        ...DraftOrderQuestionFields\n      }\n    }\n  }\n": typeof types.DraftOrderSummaryFieldsFragmentDoc,
    "\n  fragment DraftOrderDetailFields on PhotonPpDraftOrder {\n    ...DraftOrderClaimFields\n    order {\n      id\n      state\n      pharmacy {\n        id\n        name\n        address {\n          street1\n          street2\n          city\n          state\n          postalCode\n        }\n      }\n      patient {\n        __typename\n        ... on Patient {\n          id\n          demographic {\n            name {\n              first\n              last\n            }\n            dateOfBirth\n            sex\n            address {\n              state\n            }\n          }\n          clinical {\n            allergies {\n              name\n            }\n          }\n        }\n      }\n      prescriptions {\n        ...NetworkPrescriptionFields\n      }\n      questions {\n        ...DraftOrderQuestionFields\n      }\n    }\n  }\n": typeof types.DraftOrderDetailFieldsFragmentDoc,
    "\n  fragment DraftOrderResultFields on PhotonPpDraftOrderResult {\n    __typename\n    ... on PhotonPpDraftOrderPayload {\n      draftOrder {\n        ...DraftOrderDetailFields\n      }\n    }\n    ... on InvalidInputError {\n      code\n      message\n    }\n    ... on NotFoundError {\n      code\n      message\n    }\n    ... on ConflictError {\n      code\n      message\n    }\n    ... on UnauthorizedError {\n      code\n      message\n    }\n    ... on UpstreamServiceError {\n      code\n      message\n    }\n  }\n": typeof types.DraftOrderResultFieldsFragmentDoc,
    "\n  query PhotonPpDraftOrders($filter: PhotonPpDraftOrderFilter!, $first: Int, $after: String) {\n    photonPpDraftOrders(filter: $filter, first: $first, after: $after) {\n      __typename\n      ... on PhotonPpDraftOrderConnection {\n        nodes {\n          ...DraftOrderSummaryFields\n        }\n        endCursor\n        hasNextPage\n        totalCount\n      }\n      ... on UnauthorizedError {\n        code\n        message\n      }\n      ... on UpstreamServiceError {\n        code\n        message\n      }\n    }\n  }\n": typeof types.PhotonPpDraftOrdersDocument,
    "\n  query PhotonPpDraftOrderCounts {\n    toReview: photonPpDraftOrders(filter: UNCLAIMED, first: 1) {\n      ... on PhotonPpDraftOrderConnection {\n        totalCount\n      }\n    }\n    myReviews: photonPpDraftOrders(filter: MY_REVIEWS, first: 1) {\n      ... on PhotonPpDraftOrderConnection {\n        totalCount\n      }\n    }\n    waitingOnPatient: photonPpDraftOrders(filter: WAITING_ON_PATIENT, first: 1) {\n      ... on PhotonPpDraftOrderConnection {\n        totalCount\n      }\n    }\n    closed: photonPpDraftOrders(filter: CLOSED, first: 1) {\n      ... on PhotonPpDraftOrderConnection {\n        totalCount\n      }\n    }\n  }\n": typeof types.PhotonPpDraftOrderCountsDocument,
    "\n  query PhotonPpDraftOrder($id: ID!) {\n    photonPpDraftOrder(id: $id) {\n      ...DraftOrderResultFields\n    }\n  }\n": typeof types.PhotonPpDraftOrderDocument,
    "\n  query PhotonPpPatientHistory($patientId: ID!) {\n    photonPpPatientOrders(patientId: $patientId, first: 25) {\n      __typename\n      ... on PhotonPpPatientOrderConnection {\n        nodes {\n          organizationId\n          patientId\n          createdAt\n          order {\n            id\n            state\n            prescriptions {\n              id\n              treatment {\n                id\n                name\n              }\n            }\n          }\n        }\n      }\n      ... on NotFoundError {\n        code\n        message\n      }\n      ... on UnauthorizedError {\n        code\n        message\n      }\n      ... on InvalidInputError {\n        code\n        message\n      }\n      ... on UpstreamServiceError {\n        code\n        message\n      }\n    }\n  }\n": typeof types.PhotonPpPatientHistoryDocument,
    "\n  mutation ClaimDraftOrder($id: ID!, $metadata: RequestMetadata!) {\n    claimDraftOrder(id: $id, metadata: $metadata) {\n      ...DraftOrderResultFields\n    }\n  }\n": typeof types.ClaimDraftOrderDocument,
    "\n  mutation RejectDraftOrder($id: ID!, $reason: String!, $metadata: RequestMetadata!) {\n    rejectDraftOrder(id: $id, reason: $reason, metadata: $metadata) {\n      ...DraftOrderResultFields\n    }\n  }\n": typeof types.RejectDraftOrderDocument,
    "\n  mutation SetDraftOrderWaitingForPatient(\n    $id: ID!\n    $waitingForPatient: Boolean!\n    $metadata: RequestMetadata!\n  ) {\n    setDraftOrderWaitingForPatient(\n      id: $id\n      waitingForPatient: $waitingForPatient\n      metadata: $metadata\n    ) {\n      ...DraftOrderResultFields\n    }\n  }\n": typeof types.SetDraftOrderWaitingForPatientDocument,
    "\n  mutation ApproveDraftOrder($id: ID!, $prescriptionIds: [ID!]!, $metadata: RequestMetadata!) {\n    approveDraftOrder(id: $id, prescriptionIds: $prescriptionIds, metadata: $metadata) {\n      ...DraftOrderResultFields\n    }\n  }\n": typeof types.ApproveDraftOrderDocument,
    "\n  mutation AddDraftOrderQuestions(\n    $id: ID!\n    $questions: [DraftOrderQuestionInput!]!\n    $metadata: RequestMetadata!\n  ) {\n    addDraftOrderQuestions(id: $id, questions: $questions, metadata: $metadata) {\n      __typename\n      ... on DraftOrderQuestionsPayload {\n        order {\n          id\n        }\n      }\n      ... on InvalidInputError {\n        code\n        message\n      }\n      ... on NotFoundError {\n        code\n        message\n      }\n      ... on ConflictError {\n        code\n        message\n      }\n      ... on UnauthorizedError {\n        code\n        message\n      }\n      ... on UpstreamServiceError {\n        code\n        message\n      }\n    }\n  }\n": typeof types.AddDraftOrderQuestionsDocument,
    "\n  mutation NetworkPrescription($prescription: PrescriptionInput, $metadata: RequestMetadata!) {\n    prescription(prescription: $prescription, metadata: $metadata) {\n      __typename\n      ... on PrescriptionPayload {\n        prescription {\n          ...NetworkPrescriptionFields\n        }\n        unappliedChanges {\n          ...NetworkChangeFields\n        }\n      }\n      ... on AmbiguousPrescriptionMatch {\n        reason\n      }\n      ... on UnauthorizedError {\n        code\n        message\n      }\n      ... on UpstreamServiceError {\n        code\n        message\n      }\n    }\n  }\n": typeof types.NetworkPrescriptionDocument,
};
const documents: Documents = {
    "\n  fragment NetworkPrescriptionFields on Prescription {\n    id\n    status\n    treatment {\n      id\n      name\n      rxNormId\n      ndc\n    }\n    instructions\n    dispense {\n      quantity\n      unit\n      daysSupply\n      refillsAllowed\n      dispenseAsWritten\n    }\n    clinical {\n      notes\n      diagnoses {\n        icd10Code\n      }\n    }\n    screeningAlerts {\n      severity\n      type\n      description\n    }\n    signing {\n      state\n      contentHash\n    }\n  }\n": types.NetworkPrescriptionFieldsFragmentDoc,
    "\n  fragment NetworkChangeFields on Change {\n    key\n    label\n    status\n    severity\n    reason\n  }\n": types.NetworkChangeFieldsFragmentDoc,
    "\n  fragment DraftOrderQuestionFields on OrderQuestion {\n    id\n    key\n    text\n    reason\n    authorOrganizationId\n    answer {\n      text\n      boolean\n      date\n      choices\n    }\n    answeredAt\n    createdAt\n  }\n": types.DraftOrderQuestionFieldsFragmentDoc,
    "\n  fragment DraftOrderClaimFields on PhotonPpDraftOrder {\n    id\n    createdAt\n    claim {\n      organizationId\n      claimedAt\n      waitingForPatient\n      patientId\n      claimedByUserId\n      claimedByMe\n    }\n    outcome {\n      status\n      closedAt\n      orderId\n      rejectionReason\n    }\n  }\n": types.DraftOrderClaimFieldsFragmentDoc,
    "\n  fragment DraftOrderSummaryFields on PhotonPpDraftOrder {\n    ...DraftOrderClaimFields\n    order {\n      id\n      state\n      patient {\n        __typename\n        ... on Patient {\n          id\n          demographic {\n            name {\n              first\n              last\n            }\n            dateOfBirth\n            address {\n              state\n            }\n          }\n        }\n      }\n      prescriptions {\n        id\n        treatment {\n          id\n          name\n        }\n      }\n      questions {\n        ...DraftOrderQuestionFields\n      }\n    }\n  }\n": types.DraftOrderSummaryFieldsFragmentDoc,
    "\n  fragment DraftOrderDetailFields on PhotonPpDraftOrder {\n    ...DraftOrderClaimFields\n    order {\n      id\n      state\n      pharmacy {\n        id\n        name\n        address {\n          street1\n          street2\n          city\n          state\n          postalCode\n        }\n      }\n      patient {\n        __typename\n        ... on Patient {\n          id\n          demographic {\n            name {\n              first\n              last\n            }\n            dateOfBirth\n            sex\n            address {\n              state\n            }\n          }\n          clinical {\n            allergies {\n              name\n            }\n          }\n        }\n      }\n      prescriptions {\n        ...NetworkPrescriptionFields\n      }\n      questions {\n        ...DraftOrderQuestionFields\n      }\n    }\n  }\n": types.DraftOrderDetailFieldsFragmentDoc,
    "\n  fragment DraftOrderResultFields on PhotonPpDraftOrderResult {\n    __typename\n    ... on PhotonPpDraftOrderPayload {\n      draftOrder {\n        ...DraftOrderDetailFields\n      }\n    }\n    ... on InvalidInputError {\n      code\n      message\n    }\n    ... on NotFoundError {\n      code\n      message\n    }\n    ... on ConflictError {\n      code\n      message\n    }\n    ... on UnauthorizedError {\n      code\n      message\n    }\n    ... on UpstreamServiceError {\n      code\n      message\n    }\n  }\n": types.DraftOrderResultFieldsFragmentDoc,
    "\n  query PhotonPpDraftOrders($filter: PhotonPpDraftOrderFilter!, $first: Int, $after: String) {\n    photonPpDraftOrders(filter: $filter, first: $first, after: $after) {\n      __typename\n      ... on PhotonPpDraftOrderConnection {\n        nodes {\n          ...DraftOrderSummaryFields\n        }\n        endCursor\n        hasNextPage\n        totalCount\n      }\n      ... on UnauthorizedError {\n        code\n        message\n      }\n      ... on UpstreamServiceError {\n        code\n        message\n      }\n    }\n  }\n": types.PhotonPpDraftOrdersDocument,
    "\n  query PhotonPpDraftOrderCounts {\n    toReview: photonPpDraftOrders(filter: UNCLAIMED, first: 1) {\n      ... on PhotonPpDraftOrderConnection {\n        totalCount\n      }\n    }\n    myReviews: photonPpDraftOrders(filter: MY_REVIEWS, first: 1) {\n      ... on PhotonPpDraftOrderConnection {\n        totalCount\n      }\n    }\n    waitingOnPatient: photonPpDraftOrders(filter: WAITING_ON_PATIENT, first: 1) {\n      ... on PhotonPpDraftOrderConnection {\n        totalCount\n      }\n    }\n    closed: photonPpDraftOrders(filter: CLOSED, first: 1) {\n      ... on PhotonPpDraftOrderConnection {\n        totalCount\n      }\n    }\n  }\n": types.PhotonPpDraftOrderCountsDocument,
    "\n  query PhotonPpDraftOrder($id: ID!) {\n    photonPpDraftOrder(id: $id) {\n      ...DraftOrderResultFields\n    }\n  }\n": types.PhotonPpDraftOrderDocument,
    "\n  query PhotonPpPatientHistory($patientId: ID!) {\n    photonPpPatientOrders(patientId: $patientId, first: 25) {\n      __typename\n      ... on PhotonPpPatientOrderConnection {\n        nodes {\n          organizationId\n          patientId\n          createdAt\n          order {\n            id\n            state\n            prescriptions {\n              id\n              treatment {\n                id\n                name\n              }\n            }\n          }\n        }\n      }\n      ... on NotFoundError {\n        code\n        message\n      }\n      ... on UnauthorizedError {\n        code\n        message\n      }\n      ... on InvalidInputError {\n        code\n        message\n      }\n      ... on UpstreamServiceError {\n        code\n        message\n      }\n    }\n  }\n": types.PhotonPpPatientHistoryDocument,
    "\n  mutation ClaimDraftOrder($id: ID!, $metadata: RequestMetadata!) {\n    claimDraftOrder(id: $id, metadata: $metadata) {\n      ...DraftOrderResultFields\n    }\n  }\n": types.ClaimDraftOrderDocument,
    "\n  mutation RejectDraftOrder($id: ID!, $reason: String!, $metadata: RequestMetadata!) {\n    rejectDraftOrder(id: $id, reason: $reason, metadata: $metadata) {\n      ...DraftOrderResultFields\n    }\n  }\n": types.RejectDraftOrderDocument,
    "\n  mutation SetDraftOrderWaitingForPatient(\n    $id: ID!\n    $waitingForPatient: Boolean!\n    $metadata: RequestMetadata!\n  ) {\n    setDraftOrderWaitingForPatient(\n      id: $id\n      waitingForPatient: $waitingForPatient\n      metadata: $metadata\n    ) {\n      ...DraftOrderResultFields\n    }\n  }\n": types.SetDraftOrderWaitingForPatientDocument,
    "\n  mutation ApproveDraftOrder($id: ID!, $prescriptionIds: [ID!]!, $metadata: RequestMetadata!) {\n    approveDraftOrder(id: $id, prescriptionIds: $prescriptionIds, metadata: $metadata) {\n      ...DraftOrderResultFields\n    }\n  }\n": types.ApproveDraftOrderDocument,
    "\n  mutation AddDraftOrderQuestions(\n    $id: ID!\n    $questions: [DraftOrderQuestionInput!]!\n    $metadata: RequestMetadata!\n  ) {\n    addDraftOrderQuestions(id: $id, questions: $questions, metadata: $metadata) {\n      __typename\n      ... on DraftOrderQuestionsPayload {\n        order {\n          id\n        }\n      }\n      ... on InvalidInputError {\n        code\n        message\n      }\n      ... on NotFoundError {\n        code\n        message\n      }\n      ... on ConflictError {\n        code\n        message\n      }\n      ... on UnauthorizedError {\n        code\n        message\n      }\n      ... on UpstreamServiceError {\n        code\n        message\n      }\n    }\n  }\n": types.AddDraftOrderQuestionsDocument,
    "\n  mutation NetworkPrescription($prescription: PrescriptionInput, $metadata: RequestMetadata!) {\n    prescription(prescription: $prescription, metadata: $metadata) {\n      __typename\n      ... on PrescriptionPayload {\n        prescription {\n          ...NetworkPrescriptionFields\n        }\n        unappliedChanges {\n          ...NetworkChangeFields\n        }\n      }\n      ... on AmbiguousPrescriptionMatch {\n        reason\n      }\n      ... on UnauthorizedError {\n        code\n        message\n      }\n      ... on UpstreamServiceError {\n        code\n        message\n      }\n    }\n  }\n": types.NetworkPrescriptionDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment NetworkPrescriptionFields on Prescription {\n    id\n    status\n    treatment {\n      id\n      name\n      rxNormId\n      ndc\n    }\n    instructions\n    dispense {\n      quantity\n      unit\n      daysSupply\n      refillsAllowed\n      dispenseAsWritten\n    }\n    clinical {\n      notes\n      diagnoses {\n        icd10Code\n      }\n    }\n    screeningAlerts {\n      severity\n      type\n      description\n    }\n    signing {\n      state\n      contentHash\n    }\n  }\n"): (typeof documents)["\n  fragment NetworkPrescriptionFields on Prescription {\n    id\n    status\n    treatment {\n      id\n      name\n      rxNormId\n      ndc\n    }\n    instructions\n    dispense {\n      quantity\n      unit\n      daysSupply\n      refillsAllowed\n      dispenseAsWritten\n    }\n    clinical {\n      notes\n      diagnoses {\n        icd10Code\n      }\n    }\n    screeningAlerts {\n      severity\n      type\n      description\n    }\n    signing {\n      state\n      contentHash\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment NetworkChangeFields on Change {\n    key\n    label\n    status\n    severity\n    reason\n  }\n"): (typeof documents)["\n  fragment NetworkChangeFields on Change {\n    key\n    label\n    status\n    severity\n    reason\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment DraftOrderQuestionFields on OrderQuestion {\n    id\n    key\n    text\n    reason\n    authorOrganizationId\n    answer {\n      text\n      boolean\n      date\n      choices\n    }\n    answeredAt\n    createdAt\n  }\n"): (typeof documents)["\n  fragment DraftOrderQuestionFields on OrderQuestion {\n    id\n    key\n    text\n    reason\n    authorOrganizationId\n    answer {\n      text\n      boolean\n      date\n      choices\n    }\n    answeredAt\n    createdAt\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment DraftOrderClaimFields on PhotonPpDraftOrder {\n    id\n    createdAt\n    claim {\n      organizationId\n      claimedAt\n      waitingForPatient\n      patientId\n      claimedByUserId\n      claimedByMe\n    }\n    outcome {\n      status\n      closedAt\n      orderId\n      rejectionReason\n    }\n  }\n"): (typeof documents)["\n  fragment DraftOrderClaimFields on PhotonPpDraftOrder {\n    id\n    createdAt\n    claim {\n      organizationId\n      claimedAt\n      waitingForPatient\n      patientId\n      claimedByUserId\n      claimedByMe\n    }\n    outcome {\n      status\n      closedAt\n      orderId\n      rejectionReason\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment DraftOrderSummaryFields on PhotonPpDraftOrder {\n    ...DraftOrderClaimFields\n    order {\n      id\n      state\n      patient {\n        __typename\n        ... on Patient {\n          id\n          demographic {\n            name {\n              first\n              last\n            }\n            dateOfBirth\n            address {\n              state\n            }\n          }\n        }\n      }\n      prescriptions {\n        id\n        treatment {\n          id\n          name\n        }\n      }\n      questions {\n        ...DraftOrderQuestionFields\n      }\n    }\n  }\n"): (typeof documents)["\n  fragment DraftOrderSummaryFields on PhotonPpDraftOrder {\n    ...DraftOrderClaimFields\n    order {\n      id\n      state\n      patient {\n        __typename\n        ... on Patient {\n          id\n          demographic {\n            name {\n              first\n              last\n            }\n            dateOfBirth\n            address {\n              state\n            }\n          }\n        }\n      }\n      prescriptions {\n        id\n        treatment {\n          id\n          name\n        }\n      }\n      questions {\n        ...DraftOrderQuestionFields\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment DraftOrderDetailFields on PhotonPpDraftOrder {\n    ...DraftOrderClaimFields\n    order {\n      id\n      state\n      pharmacy {\n        id\n        name\n        address {\n          street1\n          street2\n          city\n          state\n          postalCode\n        }\n      }\n      patient {\n        __typename\n        ... on Patient {\n          id\n          demographic {\n            name {\n              first\n              last\n            }\n            dateOfBirth\n            sex\n            address {\n              state\n            }\n          }\n          clinical {\n            allergies {\n              name\n            }\n          }\n        }\n      }\n      prescriptions {\n        ...NetworkPrescriptionFields\n      }\n      questions {\n        ...DraftOrderQuestionFields\n      }\n    }\n  }\n"): (typeof documents)["\n  fragment DraftOrderDetailFields on PhotonPpDraftOrder {\n    ...DraftOrderClaimFields\n    order {\n      id\n      state\n      pharmacy {\n        id\n        name\n        address {\n          street1\n          street2\n          city\n          state\n          postalCode\n        }\n      }\n      patient {\n        __typename\n        ... on Patient {\n          id\n          demographic {\n            name {\n              first\n              last\n            }\n            dateOfBirth\n            sex\n            address {\n              state\n            }\n          }\n          clinical {\n            allergies {\n              name\n            }\n          }\n        }\n      }\n      prescriptions {\n        ...NetworkPrescriptionFields\n      }\n      questions {\n        ...DraftOrderQuestionFields\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment DraftOrderResultFields on PhotonPpDraftOrderResult {\n    __typename\n    ... on PhotonPpDraftOrderPayload {\n      draftOrder {\n        ...DraftOrderDetailFields\n      }\n    }\n    ... on InvalidInputError {\n      code\n      message\n    }\n    ... on NotFoundError {\n      code\n      message\n    }\n    ... on ConflictError {\n      code\n      message\n    }\n    ... on UnauthorizedError {\n      code\n      message\n    }\n    ... on UpstreamServiceError {\n      code\n      message\n    }\n  }\n"): (typeof documents)["\n  fragment DraftOrderResultFields on PhotonPpDraftOrderResult {\n    __typename\n    ... on PhotonPpDraftOrderPayload {\n      draftOrder {\n        ...DraftOrderDetailFields\n      }\n    }\n    ... on InvalidInputError {\n      code\n      message\n    }\n    ... on NotFoundError {\n      code\n      message\n    }\n    ... on ConflictError {\n      code\n      message\n    }\n    ... on UnauthorizedError {\n      code\n      message\n    }\n    ... on UpstreamServiceError {\n      code\n      message\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query PhotonPpDraftOrders($filter: PhotonPpDraftOrderFilter!, $first: Int, $after: String) {\n    photonPpDraftOrders(filter: $filter, first: $first, after: $after) {\n      __typename\n      ... on PhotonPpDraftOrderConnection {\n        nodes {\n          ...DraftOrderSummaryFields\n        }\n        endCursor\n        hasNextPage\n        totalCount\n      }\n      ... on UnauthorizedError {\n        code\n        message\n      }\n      ... on UpstreamServiceError {\n        code\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  query PhotonPpDraftOrders($filter: PhotonPpDraftOrderFilter!, $first: Int, $after: String) {\n    photonPpDraftOrders(filter: $filter, first: $first, after: $after) {\n      __typename\n      ... on PhotonPpDraftOrderConnection {\n        nodes {\n          ...DraftOrderSummaryFields\n        }\n        endCursor\n        hasNextPage\n        totalCount\n      }\n      ... on UnauthorizedError {\n        code\n        message\n      }\n      ... on UpstreamServiceError {\n        code\n        message\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query PhotonPpDraftOrderCounts {\n    toReview: photonPpDraftOrders(filter: UNCLAIMED, first: 1) {\n      ... on PhotonPpDraftOrderConnection {\n        totalCount\n      }\n    }\n    myReviews: photonPpDraftOrders(filter: MY_REVIEWS, first: 1) {\n      ... on PhotonPpDraftOrderConnection {\n        totalCount\n      }\n    }\n    waitingOnPatient: photonPpDraftOrders(filter: WAITING_ON_PATIENT, first: 1) {\n      ... on PhotonPpDraftOrderConnection {\n        totalCount\n      }\n    }\n    closed: photonPpDraftOrders(filter: CLOSED, first: 1) {\n      ... on PhotonPpDraftOrderConnection {\n        totalCount\n      }\n    }\n  }\n"): (typeof documents)["\n  query PhotonPpDraftOrderCounts {\n    toReview: photonPpDraftOrders(filter: UNCLAIMED, first: 1) {\n      ... on PhotonPpDraftOrderConnection {\n        totalCount\n      }\n    }\n    myReviews: photonPpDraftOrders(filter: MY_REVIEWS, first: 1) {\n      ... on PhotonPpDraftOrderConnection {\n        totalCount\n      }\n    }\n    waitingOnPatient: photonPpDraftOrders(filter: WAITING_ON_PATIENT, first: 1) {\n      ... on PhotonPpDraftOrderConnection {\n        totalCount\n      }\n    }\n    closed: photonPpDraftOrders(filter: CLOSED, first: 1) {\n      ... on PhotonPpDraftOrderConnection {\n        totalCount\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query PhotonPpDraftOrder($id: ID!) {\n    photonPpDraftOrder(id: $id) {\n      ...DraftOrderResultFields\n    }\n  }\n"): (typeof documents)["\n  query PhotonPpDraftOrder($id: ID!) {\n    photonPpDraftOrder(id: $id) {\n      ...DraftOrderResultFields\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query PhotonPpPatientHistory($patientId: ID!) {\n    photonPpPatientOrders(patientId: $patientId, first: 25) {\n      __typename\n      ... on PhotonPpPatientOrderConnection {\n        nodes {\n          organizationId\n          patientId\n          createdAt\n          order {\n            id\n            state\n            prescriptions {\n              id\n              treatment {\n                id\n                name\n              }\n            }\n          }\n        }\n      }\n      ... on NotFoundError {\n        code\n        message\n      }\n      ... on UnauthorizedError {\n        code\n        message\n      }\n      ... on InvalidInputError {\n        code\n        message\n      }\n      ... on UpstreamServiceError {\n        code\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  query PhotonPpPatientHistory($patientId: ID!) {\n    photonPpPatientOrders(patientId: $patientId, first: 25) {\n      __typename\n      ... on PhotonPpPatientOrderConnection {\n        nodes {\n          organizationId\n          patientId\n          createdAt\n          order {\n            id\n            state\n            prescriptions {\n              id\n              treatment {\n                id\n                name\n              }\n            }\n          }\n        }\n      }\n      ... on NotFoundError {\n        code\n        message\n      }\n      ... on UnauthorizedError {\n        code\n        message\n      }\n      ... on InvalidInputError {\n        code\n        message\n      }\n      ... on UpstreamServiceError {\n        code\n        message\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation ClaimDraftOrder($id: ID!, $metadata: RequestMetadata!) {\n    claimDraftOrder(id: $id, metadata: $metadata) {\n      ...DraftOrderResultFields\n    }\n  }\n"): (typeof documents)["\n  mutation ClaimDraftOrder($id: ID!, $metadata: RequestMetadata!) {\n    claimDraftOrder(id: $id, metadata: $metadata) {\n      ...DraftOrderResultFields\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation RejectDraftOrder($id: ID!, $reason: String!, $metadata: RequestMetadata!) {\n    rejectDraftOrder(id: $id, reason: $reason, metadata: $metadata) {\n      ...DraftOrderResultFields\n    }\n  }\n"): (typeof documents)["\n  mutation RejectDraftOrder($id: ID!, $reason: String!, $metadata: RequestMetadata!) {\n    rejectDraftOrder(id: $id, reason: $reason, metadata: $metadata) {\n      ...DraftOrderResultFields\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation SetDraftOrderWaitingForPatient(\n    $id: ID!\n    $waitingForPatient: Boolean!\n    $metadata: RequestMetadata!\n  ) {\n    setDraftOrderWaitingForPatient(\n      id: $id\n      waitingForPatient: $waitingForPatient\n      metadata: $metadata\n    ) {\n      ...DraftOrderResultFields\n    }\n  }\n"): (typeof documents)["\n  mutation SetDraftOrderWaitingForPatient(\n    $id: ID!\n    $waitingForPatient: Boolean!\n    $metadata: RequestMetadata!\n  ) {\n    setDraftOrderWaitingForPatient(\n      id: $id\n      waitingForPatient: $waitingForPatient\n      metadata: $metadata\n    ) {\n      ...DraftOrderResultFields\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation ApproveDraftOrder($id: ID!, $prescriptionIds: [ID!]!, $metadata: RequestMetadata!) {\n    approveDraftOrder(id: $id, prescriptionIds: $prescriptionIds, metadata: $metadata) {\n      ...DraftOrderResultFields\n    }\n  }\n"): (typeof documents)["\n  mutation ApproveDraftOrder($id: ID!, $prescriptionIds: [ID!]!, $metadata: RequestMetadata!) {\n    approveDraftOrder(id: $id, prescriptionIds: $prescriptionIds, metadata: $metadata) {\n      ...DraftOrderResultFields\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation AddDraftOrderQuestions(\n    $id: ID!\n    $questions: [DraftOrderQuestionInput!]!\n    $metadata: RequestMetadata!\n  ) {\n    addDraftOrderQuestions(id: $id, questions: $questions, metadata: $metadata) {\n      __typename\n      ... on DraftOrderQuestionsPayload {\n        order {\n          id\n        }\n      }\n      ... on InvalidInputError {\n        code\n        message\n      }\n      ... on NotFoundError {\n        code\n        message\n      }\n      ... on ConflictError {\n        code\n        message\n      }\n      ... on UnauthorizedError {\n        code\n        message\n      }\n      ... on UpstreamServiceError {\n        code\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation AddDraftOrderQuestions(\n    $id: ID!\n    $questions: [DraftOrderQuestionInput!]!\n    $metadata: RequestMetadata!\n  ) {\n    addDraftOrderQuestions(id: $id, questions: $questions, metadata: $metadata) {\n      __typename\n      ... on DraftOrderQuestionsPayload {\n        order {\n          id\n        }\n      }\n      ... on InvalidInputError {\n        code\n        message\n      }\n      ... on NotFoundError {\n        code\n        message\n      }\n      ... on ConflictError {\n        code\n        message\n      }\n      ... on UnauthorizedError {\n        code\n        message\n      }\n      ... on UpstreamServiceError {\n        code\n        message\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation NetworkPrescription($prescription: PrescriptionInput, $metadata: RequestMetadata!) {\n    prescription(prescription: $prescription, metadata: $metadata) {\n      __typename\n      ... on PrescriptionPayload {\n        prescription {\n          ...NetworkPrescriptionFields\n        }\n        unappliedChanges {\n          ...NetworkChangeFields\n        }\n      }\n      ... on AmbiguousPrescriptionMatch {\n        reason\n      }\n      ... on UnauthorizedError {\n        code\n        message\n      }\n      ... on UpstreamServiceError {\n        code\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation NetworkPrescription($prescription: PrescriptionInput, $metadata: RequestMetadata!) {\n    prescription(prescription: $prescription, metadata: $metadata) {\n      __typename\n      ... on PrescriptionPayload {\n        prescription {\n          ...NetworkPrescriptionFields\n        }\n        unappliedChanges {\n          ...NetworkChangeFields\n        }\n      }\n      ... on AmbiguousPrescriptionMatch {\n        reason\n      }\n      ... on UnauthorizedError {\n        code\n        message\n      }\n      ... on UpstreamServiceError {\n        code\n        message\n      }\n    }\n  }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;