mutation MarkOrderAsPickedUp($markOrderAsPickedUpId: ID!) {
  markOrderAsPickedUp(id: $markOrderAsPickedUpId)
}

mutation SetPreferredPharmacy($pharmacyId: String, $patientId: String) {
  setPreferredPharmacy(pharmacyId: $pharmacyId, patientId: $patientId)
}

mutation RerouteOrder($orderId: ID!, $pharmacyId: ID!, $patientSelectedPrice: Boolean) {
  rerouteOrder(
    orderId: $orderId
    pharmacyId: $pharmacyId
    patientSelectedPrice: $patientSelectedPrice
  )
}

mutation SetOrderPharmacy(
  $orderId: ID!
  $pharmacyId: ID!
  $readyBy: String
  $readyByDay: String
  $readyByTime: DateTime
  $patientSelectedPrice: Boolean
) {
  setOrderPharmacy(
    orderId: $orderId
    pharmacyId: $pharmacyId
    readyBy: $readyBy
    readyByDay: $readyByDay
    readyByTime: $readyByTime
    patientSelectedPrice: $patientSelectedPrice
  )
}

mutation UpdatePatient($patientId: ID!, $input: UpdatePatientInput!) {
  updatePatient(patientId: $patientId, input: $input) {
    id
    address {
      id
      street1
      street2
      city
      state
      postalCode
      country
    }
  }
}

mutation UpdateOrder($orderId: ID!, $input: UpdateOrderInput!) {
  updateOrder(orderId: $orderId, input: $input) {
    id
    address {
      id
      street1
      street2
      city
      state
      postalCode
      country
    }
  }
}
