name: Post Testing Link in Comment

on:
  pull_request:
    types: [opened, reopened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add boson test link
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            if (github.actor === 'dependabot[bot]') {
              console.log('Skipping comment for Dependabot PR');
              return;
            }

            let ref = "${{github.head_ref}}"
            ref = ref.replace(/\//g, "_")

            const message = `
              To see this branch's clinical app [click here](https://app-${ref}.boson.health)
              
              To see this branch's patient app [click here](https://orders-${ref}.boson.health). 
              Then open a boson test text from \`#test-text\` and copy the url
            `.trim()
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            })
