name: Auto Bump Photon

on:
  push:
    branches: [neutron]

jobs:
  bumpAndOpen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.CPR_APP_ID }}
          private_key: ${{ secrets.CPR_APP_SECRET }}
      - name: checkout photon
        uses: actions/checkout@v1
        with:
          ref: photon
      - name: merge
        run: |
          git config user.name 'GitHub'
          git config user.email 'noreply@github.com'
          git merge origin/neutron
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.generate-token.outputs.token }}
          base: photon
          branch: photons/merge
          title: 'Photon: Merge neutron into photon'
          commit-message: merge
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
