name: Auto Bump Neutron

on:
  push:
    branches: [boson]

permissions:
  contents: read
  pull-requests: write

jobs:
  bumpAndOpen:
    name: Bump neutron
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        uses: actions/create-github-app-token@v3
        id: generate-token
        with:
          app-id: ${{ secrets.CPR_APP_ID }}
          private-key: ${{ secrets.CPR_APP_SECRET }}
      - name: checkout neutron
        uses: actions/checkout@v5
        with:
          ref: neutron
          fetch-depth: 0
      - name: merge
        run: |
          git config user.name 'GitHub'
          git config user.email 'noreply@github.com'
          git merge origin/boson
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ steps.generate-token.outputs.token }}
          base: neutron
          branch: neturons/merge
          title: 'Neutron: Merge boson into neutron'
          commit-message: merge
          committer: GitHub <noreply@github.com>
