name: Merge Bot

on:
  # pull_request:
  #   types:
  #     - labeled
  #     - ready_for_review
  #     - review_request_removed
  #     - review_requested
  #     - synchronize
  #     - unlabeled
  #     - edited
  # pull_request_review:
  #   types:
  #     - dismissed
  #     - submitted
  issue_comment:
    types: [created, edited, deleted]

jobs:
  merge:
    name: Merge
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.CPR_APP_ID }}
          private_key: ${{ secrets.CPR_APP_SECRET }}
      - name: resolve pr refs
        id: refs
        uses: eficode/resolve-pr-refs@main
        with:
          token: ${{ steps.generate-token.outputs.token }}
      - name: Merge when ready
        run: |
          echo HELLO ${{ github.event.comment.body }} ${{ github.event.issue.number }}
          echo GOODBYE ${{ steps.refs.outputs.base_ref }} ${{ steps.refs.outputs.head_ref }}
          # gh pr ${{ github.event.issue.number }} merge --auto --merge
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
