name: Merge Bot

on:
  pull_request:
    types:
      - labeled
      - synchronize
      - unlabeled

jobs:
  merge:
    name: Merge
    runs-on: ubuntu-latest
    if: ${{github.event.pull_request.base.ref == 'neutron' || github.event.pull_request.base.ref == 'photon'}}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.CPR_APP_ID }}
          private_key: ${{ secrets.CPR_APP_SECRET }}
      - name: Fail if not ready
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'ready') }}
        run: |
          gh pr merge --disable-auto --merge
          exit 1
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
      - name: Merge when ready
        if: success()
        run: |
          gh pr merge --auto --merge
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
