name: Merge Bot

on:
  pull_request:
    types:
      - labeled
      - ready_for_review
      - review_request_removed
      - review_requested
      - synchronize
      - unlabeled
      - edited
  pull_request_review:
    types:
      - dismissed
      - submitted

jobs:
  merge:
    name: Merge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Fail if not ready
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'ready') }}
        run: exit 1
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.CPR_APP_ID }}
          private_key: ${{ secrets.CPR_APP_SECRET }}
      - run: gh --version
      - name: Merge when ready
        if: success()
        run: |
          GH_DEBUG=api gh pr merge --auto --merge
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
