name: Merge Bot

on:
  pull_request:
    types:
      - labeled
      - ready_for_review
      - review_request_removed
      - review_requested
      - synchronize
      - unlabeled
      - edited
  pull_request_review:
    types:
      - dismissed
      - submitted

jobs:
  merge:
    name: Merge
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ready') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.CPR_APP_ID }}
          private_key: ${{ secrets.CPR_APP_SECRET }}
      - name: Merge when ready
        run: |
          gh pr merge --auto --merge
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
