name: Publish Packages

on:
  push:
    branches:
      - photon
  # Lets us retry the action if it fails on push to photon
  workflow_dispatch:

permissions:
  id-token: write # Required for OIDC trusted publishing
  contents: write # Required for pushing git tags

jobs:
  publish:
    name: NPM Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          ref: photon
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"

      - name: Update npm for trusted publishing
        run: npm install -g npm@latest

      - name: Install Dependencies
        run: npm ci

      - name: Set Git User
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Check for version updates
        id: check
        run: |
          PACKAGE_VERSION=$(node -p "require('./packages/elements/package.json').version")
          PUBLISHED_VERSION=$(npm view @photonhealth/elements version)

          if [ "$PACKAGE_VERSION" == "$PUBLISHED_VERSION" ]; then
            echo "No version bump ($PACKAGE_VERSION already published)"
          else
            echo "Version bump found: $PUBLISHED_VERSION -> $PACKAGE_VERSION"
            echo "version=$PACKAGE_VERSION" >> "$GITHUB_OUTPUT"
          fi

      - name: Publish changed package
        run: |
          PACKAGE_VERSION="${{ steps.check.outputs.version }}"
          if [ -z "$PACKAGE_VERSION" ]
          then
              echo "No package updates found."
          else
              echo "Publishing packages/elements..."

              cd packages/elements

              PACKAGE_TAG="elements_v${PACKAGE_VERSION}"
              PACKAGE_BODY="TODO FILL OUT RELEASE NOTES for elements v$PACKAGE_VERSION"

              if [[ $PACKAGE_VERSION == *"rc"* ]]
              then
                npm publish --tag rc
              else
                npm publish
              fi

              echo "Creating GitHub release for elements version $PACKAGE_VERSION..."

              git tag -a $PACKAGE_TAG -m "$PACKAGE_BODY"
              git push origin $PACKAGE_TAG
          fi
