name: Run a DataDog Synthetic test on the patient demo
jobs:
  e2e_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Datadog Synthetic tests
        uses: DataDog/synthetics-ci-github-action@v1.3.0
        with:
          api_key: ${{ secrets.DATADOG_API_KEY }}
          app_key: ${{secrets.DD_APP_KEY}}
          public_ids: '7dw-d5w-7ss'
