name: Trigger Playwright e2e Tests on PR
on:
  workflow_dispatch:
    inputs:
      sha:
        required: true

permissions:
  contents: read

jobs:
  trigger-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v8
        id: test
        with:
          script: |
            return github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: '${{ inputs.sha }}'
            })
      - name: Get result
        run: echo "${{ steps.test.outputs.result.data }}""
      

