name: Prettier Check

on:
  push:
  pull_request:
    branches: [neutron, photon]

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Codegen
        run: npx run-many --target=codegen --all

      - name: Run Prettier
        run: npx prettier --check .
