name: Check Types

on:
  push:
  pull_request:
    branches: [neutron, photon]

jobs:
  run-linters:
    name: Run type check
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: true

      - name: Install pnpm dependencies
        run: pnpm install

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build Packages
        run: npx nx run-many --all --target=build

      - name: Run Type Check
        run: npx nx run-many --all --target=tsc
