name: Upload Source Maps to Datadog

on:
  push:
    branches: [boson, neutron, photon]

jobs:
  upload-source-maps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install @datadog/datadog-ci
        run: npm install @datadog/datadog-ci@latest

      - name: Upload source maps to Datadog
        run: |
          export DATADOG_API_KEY=${{ secrets.DATADOG_API_KEY }}
          ENV_NAME=boson # Where to get this?
          SERVICE_NAME=$(node -p "require('./package.json').name")
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          npx datadog-ci sourcemaps upload dist/apps/patient \
            --service=${SERVICE_NAME} \
            --release-version=${PACKAGE_VERSION} \
            --minified-path-prefix=https://app.${github.event.pull_request.base.ref}.health/static/js
