name: Vitest

on:
  pull_request:
    branches: ['boson']

permissions:
  contents: read

jobs:
  build:
    name: Vitest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
      - run: npm ci
      - run: npx nx run components:test
      - run: npx nx run elements:test
      - run: npx nx run app:test
      - run: npx nx run patient:test
