name: Vitest

on:
  pull_request:
    branches: ['boson']

permissions:
  contents: read

jobs:
  build:
    name: Vitest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
      # there was an issue with the rollup binary not being available in the runner https://github.com/npm/cli/issues/4828
      - name: Install Rollup
        run: npm install @rollup/rollup-linux-x64-gnu
      - run: npm ci
      - run: npm run build --if-present
      - run: npx nx run sdk:build
      - run: npx nx run components:test
      - run: npx nx run elements:test
      - run: npx nx run app:test
      - run: npx nx run patient:codegen
      - run: npx nx run patient:test
